In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import norm
from statsmodels.stats.proportion import proportion_confint

In [2]:
url  = "https://raw.githubusercontent.com/it-ces/Datasets/refs/heads/main/basesuper.csv"
df = pd.read_csv(url)
df

,Unnamed: 0,NIT,y,Ingresos de actividades ordinarias,Costo de ventas,Ganancia bruta,Otros ingresos,Gastos de ventas,Gastos de administración,Otros gastos,...,Prima de emisión,Acciones propias en cartera,Inversión suplementaria al capital asignado,Otras participaciones en el patrimonio,Superavit por revaluación,Otras reservas,Ganancias acumuladas,Patrimonio total,Total de patrimonio y pasivos,_merge
0,0,800009830.0,0,1322093.0,39724.0,1282369.0,14121.0,14483.0,180234.0,81522.0,...,6607.0,NaN,NaN,NaN,NaN,46902.0,5380400.0,5527713.0,6904653.0,both
1,1,800009830.0,0,1322093.0,39724.0,1282369.0,14121.0,14483.0,180234.0,81522.0,...,6607.0,NaN,NaN,NaN,NaN,46902.0,5380400.0,5527713.0,6904653.0,both
2,2,800009830.0,0,1322093.0,39724.0,1282369.0,14121.0,14483.0,180234.0,81522.0,...,6607.0,NaN,NaN,NaN,NaN,46902.0,5380400.0,5527713.0,6904653.0,both
3,3,800009830.0,0,1322093.0,39724.0,1282369.0,14121.0,14483.0,180234.0,81522.0,...,6607.0,NaN,NaN,NaN,NaN,46902.0,5380400.0,5527713.0,6904653.0,both
4,4,800095068.0,0,9514013.0,7554030.0,1959983.0,1665.0,436294.0,537606.0,383833.0,...,NaN,NaN,NaN,NaN,NaN,NaN,3919158.0,4291158.0,8115039.0,both
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12768,12768,901202882.0,0,0.0,0.0,0.0,0.0,100.0,170.0,83.0,...,0.0,0.0,NaN,0.0,0.0,0.0,-353.0,647.0,917.0,both
12769,12769,901209458.0,0,0.0,NaN,0.0,0.0,NaN,62450.0,374.0,...,NaN,NaN,NaN,NaN,NaN,NaN,-63454.0,-62454.0,1361958.0,both
12770,12770,901216979.0,0,258644.0,219700.0,38944.0,0.0,NaN,17653.0,1053.0,...,NaN,NaN,NaN,NaN,NaN,NaN,11791.0,36791.0,219013.0,both
12771,12771,901218142.0,0,150529.0,NaN,150529.0,0.0,NaN,52028.0,NaN,...,1509391.0,NaN,NaN,3436642.0,NaN,7042654.0,-15662.0,13871762.0,14788446.0,both
12772,12772,901240570.0,0,0.0,0.0,0.0,0.0,0.0,0.0,33294.0,...,NaN,NaN,NaN,NaN,NaN,NaN,29817457.0,31611427.0,34906901.0,both

In [3]:
df['sector']  = df['Clasificación Industrial Internacional Uniforme Versión 4 A.C'].apply(lambda row: row[0:1])

In [4]:
variables = ['var1', 'var2']
sectores = ['a', 'b', 'c']
for var in variables:
  for sector in sectores:
    print(var, sector)

var1 a
var1 b
var1 c
var2 a
var2 b
var2 c

In [5]:
for sector in df['sector'].unique():
  print(sector)

L
A
K
S
N
B
M
C
G
F
I
H
R
J
P
E
Q
D
O

In [6]:
df['sector'].value_counts()

sector
G    3595
L    1966
C    1822
F    1618
M     843
A     733
N     482
K     457
J     293
B     255
I     235
H     219
R      80
P      59
S      54
Q      35
E      17
D       9
O       1
Name: count, dtype: int64

In [7]:
vars = ['Ganancia (pérdida)',  'Total de patrimonio y pasivos']
for var in vars:
  for sector in df['sector'].unique():
    mean = df[df['sector']==sector][var].mean()
    sigma = df[df['sector']==sector][var].std()
    n = df[df['sector']==sector].shape[0]
    print(var, sector)
    print(mean, norm.interval(loc=mean, scale = sigma/(n**0.5), confidence=0.95))

Ganancia (pérdida) L
651967.0437436419 (np.float64(434791.89887837024), np.float64(869142.1886089137))
Ganancia (pérdida) A
109725.51432469304 (np.float64(-95086.35710409976), np.float64(314537.38575348584))
Ganancia (pérdida) K
876712.4048140044 (np.float64(289375.2590448052), np.float64(1464049.5505832038))
Ganancia (pérdida) S
563178.2592592592 (np.float64(286418.5708617415), np.float64(839937.947656777))
Ganancia (pérdida) N
793082.765560166 (np.float64(481220.78191457887), np.float64(1104944.7492057532))
Ganancia (pérdida) B
-1484416.4 (np.float64(-4775872.506771928), np.float64(1807039.7067719284))
Ganancia (pérdida) M
856954.4567022539 (np.float64(653721.7641052181), np.float64(1060187.1492992898))
Ganancia (pérdida) C
519883.80186608125 (np.float64(412212.9464903297), np.float64(627554.6572418328))
Ganancia (pérdida) G
425956.0030598053 (np.float64(365396.71741225617), np.float64(486515.28870735446))
Ganancia (pérdida) F
679190.653275649 (np.float64(243707.65214794019), np.float64(1114673.6544033578))
Ganancia (pérdida) I
234822.48510638298 (np.float64(-225016.18529330805), np.float64(694661.155506074))
Ganancia (pérdida) H
864129.3242009132 (np.float64(301349.47566474543), np.float64(1426909.172737081))
Ganancia (pérdida) R
421709.675 (np.float64(-21082.399227800313), np.float64(864501.7492278003))
Ganancia (pérdida) J
879090.4846416382 (np.float64(88402.59298174176), np.float64(1669778.3763015347))
Ganancia (pérdida) P
345599.27118644066 (np.float64(-249818.3608627505), np.float64(941016.9032356318))
Ganancia (pérdida) E
-191123.41176470587 (np.float64(-742626.0219329938), np.float64(360379.198403582))
Ganancia (pérdida) Q
1616705.0285714285 (np.float64(270301.34101993195), np.float64(2963108.7161229253))
Ganancia (pérdida) D
423752.44444444444 (np.float64(-48322.03445370711), np.float64(895826.923342596))
Ganancia (pérdida) O
-105486.0 (np.float64(nan), np.float64(nan))
Total de patrimonio y pasivos L
21941767.853001017 (np.float64(20173540.624512654), np.float64(23709995.08148938))
Total de patrimonio y pasivos A
24987403.720327422 (np.float64(22524937.3888538), np.float64(27449870.051801044))
Total de patrimonio y pasivos K
40062399.07002188 (np.float64(33213246.048351012), np.float64(46911552.09169275))
Total de patrimonio y pasivos S
14897964.222222222 (np.float64(10620850.456498235), np.float64(19175077.98794621))
Total de patrimonio y pasivos N
18927257.48340249 (np.float64(16081716.216431133), np.float64(21772798.750373848))
Total de patrimonio y pasivos B
25895545.988235295 (np.float64(19269847.06542207), np.float64(32521244.91104852))
Total de patrimonio y pasivos M
18683742.30723606 (np.float64(16185987.790594807), np.float64(21181496.823877312))
Total de patrimonio y pasivos C
19608521.88529089 (np.float64(18156913.247298468), np.float64(21060130.523283314))
Total de patrimonio y pasivos G
14985174.897913769 (np.float64(14228859.540283155), np.float64(15741490.255544383))
Total de patrimonio y pasivos F
22135943.377008654 (np.float64(20313850.418939877), np.float64(23958036.33507743))
Total de patrimonio y pasivos I
19562781.736170214 (np.float64(16348187.499387184), np.float64(22777375.972953245))
Total de patrimonio y pasivos H
23218862.397260275 (np.float64(18004574.665672693), np.float64(28433150.128847856))
Total de patrimonio y pasivos R
15306571.3125 (np.float64(10911916.55356795), np.float64(19701226.07143205))
Total de patrimonio y pasivos J
16954669.546075087 (np.float64(12997521.987635989), np.float64(20911817.104514185))
Total de patrimonio y pasivos P
19477173.15254237 (np.float64(14383581.6893927), np.float64(24570764.61569204))
Total de patrimonio y pasivos E
9314663.294117646 (np.float64(6458989.536674412), np.float64(12170337.05156088))
Total de patrimonio y pasivos Q
15315705.914285714 (np.float64(10452697.723657228), np.float64(20178714.1049142))
Total de patrimonio y pasivos D
18280361.666666668 (np.float64(7797514.504927721), np.float64(28763208.828405615))
Total de patrimonio y pasivos O
9798875.0 (np.float64(nan), np.float64(nan))

In [8]:

# Confidence interval mean
print(norm.interval(loc = 12, scale=4, confidence=0.95))
# Confidence interval proportion
proportion_confint(30, 130, 0.05)

(np.float64(4.160144061839784), np.float64(19.839855938160216))

(0.1583433659148782, 0.3031950956235834)